// functions/views/dashboard.js
import { BASE_STYLES } from "./baseStyles.js";

export const HTML = [
  "<!doctype html><html lang='en'><head><meta charset='utf-8'/>",
  "<meta name='viewport' content='width=device-width, initial-scale=1'/>",
  "<title>Sequence Five — Usage</title>",
  "<style>",
  BASE_STYLES,
  ".cards{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}@media(max-width:980px){.cards{grid-template-columns:1fr}}",
  ".kpi{padding:16px;border-radius:16px;border:1px solid var(--line);background:linear-gradient(180deg,rgba(255,255,255,.055),rgba(255,255,255,.025));box-shadow:var(--shadow-soft)}",
  ".kpi .label{font-size:12px;color:var(--muted)} .kpi .val{font-size:22px;font-weight:900;margin-top:6px}",
  ".rowh{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}",
  ".chart{height:260px;border-radius:16px;border:1px solid var(--line);padding:12px;background:linear-gradient(180deg,rgba(255,255,255,.04),rgba(255,255,255,.02))}",
  ".table{margin-top:14px;border:1px solid var(--line);border-radius:12px;overflow:hidden}",
  ".table table{width:100%;border-collapse:collapse;font-size:13px}",
  ".table th,.table td{padding:10px;border-bottom:1px solid #232845} .table th{text-align:left;color:#c8d0ee;font-weight:700}",
  "</style></head>",
  "<body>",
  "<div class='app'>",

    "<aside class='sidebar'>",
      "<div class='nav-brand'>",
        "<div class='logo'><img src='/images/app-logo.svg' alt='Sequence Five logo'/></div>",
        "<div class='nav-title'>Sequence Five</div>",
      "</div>",
      "<nav class='nav'>",
        "<a href='/'>",
          "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect x='3' y='3' width='7' height='7' rx='2'/><rect x='14' y='3' width='7' height='7' rx='2'/><rect x='14' y='14' width='7' height='7' rx='2'/><rect x='3' y='14' width='7' height='7' rx='2'/></svg>",
          "<span>Image Generator</span>",
        "</a>",
        "<a href='/storyboards'>",
          "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M21 15V6a2 2 0 0 0-2-2H6'/><path d='M3 7v11a2 2 0 0 0 2 2h11'/><rect x='7' y='7' width='10' height='10' rx='2'/></svg>",
          "<span>Storyboards</span>",
        "</a>",
        "<a href='/gallery'>",
          "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect x='3' y='3' width='7' height='7' rx='2'/><rect x='14' y='3' width='7' height='7' rx='2'/><rect x='14' y='14' width='7' height='7' rx='2'/><rect x='3' y='14' width='7' height='7' rx='2'/></svg>",
          "<span>Archive</span>",
        "</a>",
        "<a class='active' href='/dashboard' aria-current='page'>",
          "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M3 3v18h18'/><path d='M7 15l5-5 4 4 5-6'/></svg>",
          "<span>Usage</span>",
        "</a>",
        "<span class='sep'></span>",
        "<a href='#'>",
          "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4'/><polyline points='16 17 21 12 16 7'/><line x1='21' y1='12' x2='9' y2='12'/></svg>",
          "<span>Logout</span>",
        "</a>",
      "</nav>",
    "</aside>",

    "<main class='main'>",
      "<div class='wrap'>",

        "<div class='headerbar'>",
          "<div class='hgroup'><h1>Usage</h1><div class='sub'>Daily spend and model breakdown.</div></div>",
          "<div class='row'><label>From</label><input id='from' type='date'/><label>To</label><input id='to' type='date'/><button id='apply' class='pill'>Apply</button></div>",
        "</div>",

        "<div class='cards'>",
          "<div class='kpi'><div class='label'>Total (USD)</div><div id='kpiTotal' class='val'>$0.00</div></div>",
          "<div class='kpi'><div class='label'>OpenAI (USD)</div><div id='kpiOpenAI' class='val'>$0.00</div></div>",
          "<div class='kpi'><div class='label'>Gemini (USD)</div><div id='kpiGemini' class='val'>$0.00</div></div>",
        "</div>",

        "<div class='grid' style='margin-top:14px'>",
          "<div class='card'>",
            "<div class='rowh'><strong>Daily spend</strong><span class='hint'>USD per day</span></div>",
            "<div id='chartDaily' class='chart'></div>",
          "</div>",
          "<div class='card'>",
            "<div class='rowh'><strong>By model</strong><span class='hint'>USD by model</span></div>",
            "<div id='chartModels' class='chart'></div>",
          "</div>",
        "</div>",

        "<div class='card' style='margin-top:14px'>",
          "<div class='rowh'><strong>Day by day</strong><button id='refresh' class='pill'>Refresh</button></div>",
          "<div id='table' class='table'></div>",
        "</div>",

        "<footer class='site-footer'>Made by Sequence Five</footer>",
      "</div>",
    "</main>",
  "</div>",

  "<script src='/assets/dashboard.js'></script>",
  "</body></html>"
].join("");
