// functions/views/storyboard.js
import { BASE_STYLES } from "./baseStyles.js";

export const HTML = [
  "<!doctype html><html lang='en'><head><meta charset='utf-8'/>",
  "<meta name='viewport' content='width=device-width, initial-scale=1'/>",
  "<title>Sequence Five — Storyboard</title>",
  "<style>",
  BASE_STYLES,
  ".sb-list{margin-top:16px}",
  ".sb-item{display:grid;grid-template-columns:28px 1fr;gap:18px;margin:28px 0}",
  ".sb-rail{position:relative}",
  ".sb-rail::after{content:'';position:absolute;top:-8px;bottom:-28px;left:13px;width:2px;background:rgba(139,92,246,.28)}",
  ".sb-item:last-child .sb-rail::after{bottom:0}",
  ".sb-dot{position:relative;left:4px;top:2px;width:20px;height:20px;border-radius:50%;background:linear-gradient(180deg,#8b5cf6,#7c3aed);box-shadow:0 0 0 5px rgba(139,92,246,.18), 0 10px 24px rgba(2,6,23,.55)}",
  ".sb-card{border-radius:22px;padding:24px;background:linear-gradient(180deg, var(--glass1), var(--glass2));border:1.2px solid var(--line-soft);box-shadow:var(--shadow-soft)}",
  ".sb-inner{display:grid;grid-template-columns:1.05fr 1fr;gap:22px;align-items:center}",
  "@media (max-width:1000px){.sb-inner{grid-template-columns:1fr;}}",
  ".sb-media{border-radius:22px;overflow:hidden;background:linear-gradient(180deg, var(--glass1), var(--glass2));border:1px solid var(--line-soft);box-shadow:inset 0 1px 0 rgba(255,255,255,.04)}",
  ".sb-media img{display:block;width:100%;height:auto}",
  ".blur-up{filter:blur(12px);transform:translateZ(0);transition:filter .45s ease}.blur-up.is-loaded{filter:none}",
  ".sb-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:6px}",
  "</style></head>",
  "<body>",
  "<div class='app'>",

    "<aside class='sidebar'>",
      "<div class='nav-brand'>",
        "<div class='logo'><img src='/images/app-logo.svg' alt='Sequence Five logo'/></div>",
        "<div class='nav-title'>Sequence Five</div>",
      "</div>",
      "<nav class='nav'>",
        "<a href='/'>",
          "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect x='3' y='3' width='7' height='7' rx='2'/><rect x='14' y='3' width='7' height='7' rx='2'/><rect x='14' y='14' width='7' height='7' rx='2'/><rect x='3' y='14' width='7' height='7' rx='2'/></svg>",
          "<span>Image Generator</span>",
        "</a>",
        "<a class='active' href='/storyboards'>",
          "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M21 15V6a2 2 0 0 0-2-2H6'/><path d='M3 7v11a2 2 0 0 0 2 2h11'/><rect x='7' y='7' width='10' height='10' rx='2'/></svg>",
          "<span>Storyboards</span>",
        "</a>",
        "<a href='/gallery'>",
          "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect x='3' y='3' width='7' height='7' rx='2'/><rect x='14' y='3' width='7' height='7' rx='2'/><rect x='14' y='14' width='7' height='7' rx='2'/><rect x='3' y='14' width='7' height='7' rx='2'/></svg>",
          "<span>Archive</span>",
        "</a>",
        "<a href='/dashboard'>",
          "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M3 3v18h18'/><path d='M7 15l5-5 4 4 5-6'/></svg>",
          "<span>Usage</span>",
        "</a>",
        "<span class='sep'></span>",
        "<a href='#'>",
          "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4'/><polyline points='16 17 21 12 16 7'/></svg>",
          "<span>Logout</span>",
        "</a>",
      "</nav>",
    "</aside>",

    "<main class='main'>",
      "<div class='wrap'>",
        "<div class='headerbar'><div class='hgroup'><h1>Storyboard</h1></div></div>",
        "<div class='card' id='head'><div class='hint'>Loading…</div></div>",
        "<div class='sb-list' id='itemsWrap'></div>",
        "<div id='empty' class='hint' style='display:none'>No items yet.</div>",
        "<footer class='site-footer'>Made by Sequence Five</footer>",
      "</div>",
    "</main>",
  "</div>",

  "<script src='/assets/storyboard.js'></script>",
  "</body></html>"
].join("");
