// functions/views/storyboards.js
import { BASE_STYLES } from "./baseStyles.js";

export const HTML = [
  "<!doctype html><html lang='en'><head><meta charset='utf-8'/>",
  "<meta name='viewport' content='width=device-width, initial-scale=1'/>",
  "<title>Sequence Five — Storyboards</title>",
  "<style>", BASE_STYLES, "</style></head>",
  "<body>",
  "<div class='app'>",

    "<aside class='sidebar'>",
      "<div class='nav-brand'>",
        "<div class='logo'><img src='/images/app-logo.svg' alt='Sequence Five logo'/></div>",
        "<div class='nav-title'>Sequence Five</div>",
      "</div>",
      "<nav class='nav'>",
        "<a href='/'>",
          "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect x='3' y='3' width='7' height='7' rx='2'/><rect x='14' y='3' width='7' height='7' rx='2'/><rect x='14' y='14' width='7' height='7' rx='2'/><rect x='3' y='14' width='7' height='7' rx='2'/></svg>",
          "<span>Image Generator</span>",
        "</a>",
        "<a class='active' href='/storyboards' aria-current='page'>",
          "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M21 15V6a2 2 0 0 0-2-2H6'/><path d='M3 7v11a2 2 0 0 0 2 2h11'/><rect x='7' y='7' width='10' height='10' rx='2'/></svg>",
          "<span>Storyboards</span>",
        "</a>",
        "<a href='/gallery'>",
          "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect x='3' y='3' width='7' height='7' rx='2'/><rect x='14' y='3' width='7' height='7' rx='2'/><rect x='14' y='14' width='7' height='7' rx='2'/><rect x='3' y='14' width='7' height='7' rx='2'/></svg>",
          "<span>Archive</span>",
        "</a>",
        "<a href='/dashboard'>",
          "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M3 3v18h18'/><path d='M7 15l5-5 4 4 5-6'/></svg>",
          "<span>Usage</span>",
        "</a>",
        "<span class='sep'></span>",
        "<a href='#'>",
          "<svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4'/><polyline points='16 17 21 12 16 7'/></svg>",
          "<span>Logout</span>",
        "</a>",
      "</nav>",
    "</aside>",

    "<main class='main'>",
      "<div class='wrap'>",
        "<div class='headerbar'>",
          "<div class='hgroup'><h1>Storyboards</h1><div class='sub'>Create and organize scenes.</div></div>",
        "</div>",

        "<div class='card' id='creator'>",
          "<h3 style='margin:0 0 10px 0'>Create a Storyboard</h3>",
          "<label>Title</label><input id='title' placeholder='e.g., Launch Teaser — Scene 03'/>",
          "<label style='margin-top:8px'>Short description</label><textarea id='desc' placeholder='What is this storyboard for?'></textarea>",
          "<div class='row' style='margin-top:12px'><button id='create' class='btn'>Create</button>",
          "<span class='hint'>You can add images after creating.</span></div>",
        "</div>",

        "<div class='card' style='margin-top:20px'>",
          "<div class='row' style='justify-content:space-between;align-items:center'>",
            "<strong>Your Storyboards</strong>",
            "<button id='refresh' class='pill'>Refresh</button>",
          "</div>",
          "<div id='list' style='margin-top:12px'></div>",
          "<div id='empty' class='hint' style='display:none'>No storyboards yet.</div>",
        "</div>",

        "<footer class='site-footer'>Made by Sequence Five</footer>",
      "</div>",
    "</main>",
  "</div>",

  "<script>",
  "(function(){",
  "  function g(id){return document.getElementById(id)};",
  "  function text(s){return document.createTextNode(s==null?'':String(s))};",

  "  function boardCard(sb){",
  "    var wrap=document.createElement('div'); wrap.className='card'; wrap.style.margin='10px 0';",
  "    var row=document.createElement('div'); row.className='row'; row.style.justifyContent='space-between';",
  "    var left=document.createElement('div');",
  "    var title=document.createElement('div'); title.style.fontWeight='700'; title.appendChild(text(sb.title||''));",
  "    var desc=document.createElement('div'); desc.className='hint'; desc.appendChild(text(sb.description||''));",
  "    var meta=document.createElement('div'); meta.className='hint'; meta.appendChild(text((sb.createdAt?new Date(sb.createdAt).toLocaleString():'' )+' • '+(sb.itemCount||0)+' item(s)'));",
  "    left.appendChild(title); left.appendChild(desc); left.appendChild(meta);",
  "    var right=document.createElement('div'); right.className='row';",
  "    var open=document.createElement('a'); open.className='pill'; open.href='/storyboard?id='+(sb.id||''); open.appendChild(text('Open ▶'));",
  "    right.appendChild(open);",
  "    row.appendChild(left); row.appendChild(right); wrap.appendChild(row);",
  "    return wrap;",
  "  }",

  "  async function load(){",
  "    var list=g('list'); list.innerHTML='<div class=\"hint\"><span class=\"spinner\"></span> Loading…</div>';",
  "    try{",
  "      var r=await fetch('/api/storyboards'); var j=await r.json(); if(!r.ok) throw new Error(j.error||'Failed');",
  "      var arr=j.storyboards||[];",
  "      if(!arr.length){ g('empty').style.display='block'; list.innerHTML=''; return; }",
  "      g('empty').style.display='none'; list.innerHTML='';",
  "      arr.forEach(function(sb){ list.appendChild(boardCard(sb)); });",
  "    }catch(e){ list.innerHTML='<div class=\"hint\">'+(e.message||e)+'</div>'; }",
  "  }",

  "  g('create').addEventListener('click', async function(){",
  "    var btn=this; var title=g('title').value.trim(); var desc=g('desc').value.trim();",
  "    if(!title){ alert('Please enter a title'); return; }",
  "    btn.disabled=true; btn.textContent='Creating…';",
  "    try{",
  "      var r=await fetch('/api/storyboards',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:title,description:desc})});",
  "      var j=await r.json(); if(!r.ok) throw new Error(j.error||'Failed');",
  "      location.href='/storyboard?id='+encodeURIComponent(j.id);",
  "    }catch(e){ alert(e.message||e); }finally{ btn.disabled=false; btn.textContent='Create'; }",
  "  });",

  "  g('refresh').addEventListener('click', load);",
  "  load();",
  "})();",
  "</script>",

  "</body></html>"
].join("");
