// functions/views/storyboards.js
import { BASE_STYLES } from "./baseStyles.js";

export const HTML = [
  "<!doctype html><html lang='en'><head><meta charset='utf-8'/>",
  "<meta name='viewport' content='width=device-width, initial-scale=1'/>",
  "<link rel='preconnect' href='https://firebasestorage.googleapis.com' crossorigin>",
  "<title>Sequence Five Generator — Storyboards</title><style>", BASE_STYLES, "</style></head>",
  "<body><div class='wrap'>",

  "<header>",
    "<div class='brand'>",
      "<div class='logo-wrap'><img class='logo-img' src='https://www.sequencefive.com/images/sequencefive-logo-navbar.svg' alt='Sequence Five logo'/></div>",
      "<span>Sequence Five Generator</span>",
    "</div>",
    "<nav>",
      "<a href='/'>Text-To-Image</a>",
      "<a href='/img2img'>Image-To-Image</a>",
      "<a href='/gallery'>Gallery</a>",
      "<a class='active' href='/storyboards'>Storyboards</a>",
    "</nav>",
  "</header>",

  "<div class='card' id='creator'>",
    "<h3 style='margin:0 0 10px 0'>Create a Storyboard</h3>",
    "<label>Title</label><input id='title' placeholder='e.g., Launch Teaser — Scene 03'/>",
    "<label style='margin-top:8px'>Short description</label><textarea id='desc' placeholder='What is this storyboard for?'></textarea>",
    "<div class='row' style='margin-top:12px'><button id='create' class='btn'>Create</button>",
    "<span class='hint'>You can add images after creating.</span></div>",
  "</div>",

  "<div class='card' style='margin-top:20px'>",
    "<div class='row' style='justify-content:space-between;align-items:center'>",
      "<strong>Your Storyboards</strong>",
      "<button id='refresh' class='pill'>Refresh</button>",
    "</div>",
    "<div id='list' style='margin-top:12px'></div>",
    "<div id='empty' class='hint' style='display:none'>No storyboards yet.</div>",
  "</div>",

  "<footer class='site-footer'>Made by Sequence Five</footer>",

  "<script>",
  "(function(){",
  "  function g(id){return document.getElementById(id)};",
  "  function text(s){return document.createTextNode(s==null?'':String(s))};",

  "  function boardCard(sb){",
  "    var wrap=document.createElement('div'); wrap.className='card'; wrap.style.margin='10px 0';",
  "    var row=document.createElement('div'); row.className='row'; row.style.justifyContent='space-between';",
  "    var left=document.createElement('div');",
  "    var title=document.createElement('div'); title.style.fontWeight='700'; title.appendChild(text(sb.title||''));",
  "    var desc=document.createElement('div'); desc.className='hint'; desc.appendChild(text(sb.description||''));",
  "    var meta=document.createElement('div'); meta.className='hint'; meta.appendChild(text((sb.createdAt?new Date(sb.createdAt).toLocaleString():'')+' • '+(sb.itemCount||0)+' item(s)'));",
  "    left.appendChild(title); left.appendChild(desc); left.appendChild(meta);",
  "    var right=document.createElement('div'); right.className='row';",
  "    var open=document.createElement('a'); open.className='pill'; open.href='/storyboard?id='+(sb.id||''); open.appendChild(text('Open ▶'));",
  "    right.appendChild(open);",
  "    row.appendChild(left); row.appendChild(right); wrap.appendChild(row);",
  "    return wrap;",
  "  }",

  "  async function load(){",
  "    var list=g('list'); list.innerHTML='<div class=\"hint\"><span class=\"spinner\"></span> Loading…</div>';",
  "    try{",
  "      var r=await fetch('/api/storyboards'); var j=await r.json(); if(!r.ok) throw new Error(j.error||'Failed');",
  "      var arr=j.storyboards||[];",
  "      if(!arr.length){ g('empty').style.display='block'; list.innerHTML=''; return; }",
  "      g('empty').style.display='none'; list.innerHTML='';",
  "      arr.forEach(function(sb){ list.appendChild(boardCard(sb)); });",
  "    }catch(e){ list.innerHTML='<div class=\"hint\">'+(e.message||e)+'</div>'; }",
  "  }",

  "  g('create').addEventListener('click', async function(){",
  "    var btn=this; var title=g('title').value.trim(); var desc=g('desc').value.trim();",
  "    if(!title){ alert('Please enter a title'); return; }",
  "    btn.disabled=true; btn.textContent='Creating…';",
  "    try{",
  "      var r=await fetch('/api/storyboards',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:title,description:desc})});",
  "      var j=await r.json(); if(!r.ok) throw new Error(j.error||'Failed');",
  "      location.href='/storyboard?id='+encodeURIComponent(j.id);",
  "    }catch(e){ alert(e.message||e); }finally{ btn.disabled=false; btn.textContent='Create'; }",
  "  });",

  "  g('refresh').addEventListener('click', load);",
  "  load();",
  "})();",
  "</script>",

  "</div></body></html>"
].join("");
